# Generated by Django 4.0.1 on 2022-01-17 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=128)),
                ('vin_number', models.CharField(max_length=128)),
                ('state_number', models.CharField(max_length=128)),
                ('consumption_per_100', models.FloatField(default=8.0)),
                ('car_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('tank_residue', models.FloatField(default=0)),
                ('refueling', models.FloatField(blank=True, default=0, null=True)),
                ('start_mileage', models.PositiveIntegerField()),
                ('end_mileage', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='waybill.car')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
